"""add_password_plain

Revision ID: 1e9b1f3ceef0
Revises: f632343d3b38
Create Date: 2026-02-23 20:54:05.017363+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9b1f3ceef0'
down_revision: Union[str, None] = 'f632343d3b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password_plain', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'password_plain')
    # ### end Alembic commands ###
