"""agregar gestion de practicas e intentos 4.3.4

Revision ID: 4d56aef74793
Revises: c938e451b03f
Create Date: 2026-01-08 05:48:06.666075+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d56aef74793'
down_revision: Union[str, None] = 'c938e451b03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Crear tipo ENUM para EstadoSesion
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE estadosesion AS ENUM ('iniciada', 'en_progreso', 'pausada', 'completada', 'abandonada');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerta_estudiante', sa.Column('fecha_lectura', sa.DateTime(), nullable=True))
    op.add_column('alerta_estudiante', sa.Column('fecha_resolucion', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_alerta_estudiante_id'), 'alerta_estudiante', ['id'], unique=False)
    op.add_column('perfil_estudiante', sa.Column('consecutivas_correctas_suma', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('consecutivas_correctas_resta', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('consecutivas_correctas_mult', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('consecutivas_correctas_div', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('varianza_velocidad', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('fecha_ultima_clasificacion', sa.DateTime(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('umbral_promocion_personalizado', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('total_sesiones', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('practicas_perfectas_consecutivas', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('historial_promociones', sa.JSON(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('alertas_activas', sa.JSON(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('ultima_actividad', sa.DateTime(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('dias_sin_practicar', sa.Integer(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('perfil_estudiante', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
    op.alter_column('perfil_estudiante', 'precision_ultimos_15',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('perfil_estudiante', 'velocidad_promedio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('perfil_estudiante', 'sesiones_en_nivel_actual',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('perfil_estudiante', 'varianza_rendimiento')
    op.drop_column('perfil_estudiante', 'fecha_ultima_actualizacion')
    op.drop_column('perfil_estudiante', 'total_correctas_nivel_actual')
    op.drop_column('perfil_estudiante', 'consecutivas_correctas')
    op.add_column('prueba_diagnostica', sa.Column('suma_nivel1_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('suma_nivel2_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('suma_tiempo_total', sa.Integer(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('resta_nivel1_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('resta_nivel2_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('resta_tiempo_total', sa.Integer(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('mult_nivel1_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('mult_nivel2_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('mult_tiempo_total', sa.Integer(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('div_nivel1_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('div_nivel2_correcto', sa.Boolean(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('div_tiempo_total', sa.Integer(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('nivel_suma_asignado', sa.Integer(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('nivel_resta_asignado', sa.Integer(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('nivel_mult_asignado', sa.Integer(), nullable=True))
    op.add_column('prueba_diagnostica', sa.Column('nivel_div_asignado', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prueba_diagnostica_id'), 'prueba_diagnostica', ['id'], unique=False)
    op.add_column('sesion_practica', sa.Column('estado', sa.Enum('iniciada', 'en_progreso', 'pausada', 'completada', 'abandonada', name='estadosesion'), nullable=False))
    op.add_column('sesion_practica', sa.Column('progreso_actual', sa.Integer(), nullable=True))
    op.add_column('sesion_practica', sa.Column('fecha_ultima_actividad', sa.DateTime(), nullable=True))
    op.add_column('sesion_practica', sa.Column('nivel_actual_inicio', sa.Integer(), nullable=True))
    op.add_column('sesion_practica', sa.Column('nivel_suma_inicio', sa.Integer(), nullable=True))
    op.add_column('sesion_practica', sa.Column('nivel_resta_inicio', sa.Integer(), nullable=True))
    op.add_column('sesion_practica', sa.Column('nivel_multiplicacion_inicio', sa.Integer(), nullable=True))
    op.add_column('sesion_practica', sa.Column('nivel_division_inicio', sa.Integer(), nullable=True))
    op.add_column('sesion_practica', sa.Column('problemas_ids', sa.JSON(), nullable=True))
    op.add_column('sesion_practica', sa.Column('operaciones_incluidas', sa.JSON(), nullable=True))
    op.add_column('sesion_practica', sa.Column('ratio_dificultad', sa.JSON(), nullable=True))
    op.add_column('sesion_practica', sa.Column('cambios_nivel', sa.JSON(), nullable=True))
    op.add_column('sesion_practica', sa.Column('perfil_al_momento', sa.String(length=50), nullable=True))
    op.add_column('sesion_practica', sa.Column('velocidad_sospechosa', sa.Boolean(), nullable=True))
    op.add_column('sesion_practica', sa.Column('patron_sospechoso', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_sesion_practica_id'), 'sesion_practica', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesion_practica_id'), table_name='sesion_practica')
    op.drop_column('sesion_practica', 'patron_sospechoso')
    op.drop_column('sesion_practica', 'velocidad_sospechosa')
    op.drop_column('sesion_practica', 'perfil_al_momento')
    op.drop_column('sesion_practica', 'cambios_nivel')
    op.drop_column('sesion_practica', 'ratio_dificultad')
    op.drop_column('sesion_practica', 'operaciones_incluidas')
    op.drop_column('sesion_practica', 'problemas_ids')
    op.drop_column('sesion_practica', 'nivel_division_inicio')
    op.drop_column('sesion_practica', 'nivel_multiplicacion_inicio')
    op.drop_column('sesion_practica', 'nivel_resta_inicio')
    op.drop_column('sesion_practica', 'nivel_suma_inicio')
    op.drop_column('sesion_practica', 'nivel_actual_inicio')
    op.drop_column('sesion_practica', 'fecha_ultima_actividad')
    op.drop_column('sesion_practica', 'progreso_actual')
    op.drop_column('sesion_practica', 'estado')
    op.drop_index(op.f('ix_prueba_diagnostica_id'), table_name='prueba_diagnostica')
    op.drop_column('prueba_diagnostica', 'nivel_div_asignado')
    op.drop_column('prueba_diagnostica', 'nivel_mult_asignado')
    op.drop_column('prueba_diagnostica', 'nivel_resta_asignado')
    op.drop_column('prueba_diagnostica', 'nivel_suma_asignado')
    op.drop_column('prueba_diagnostica', 'div_tiempo_total')
    op.drop_column('prueba_diagnostica', 'div_nivel2_correcto')
    op.drop_column('prueba_diagnostica', 'div_nivel1_correcto')
    op.drop_column('prueba_diagnostica', 'mult_tiempo_total')
    op.drop_column('prueba_diagnostica', 'mult_nivel2_correcto')
    op.drop_column('prueba_diagnostica', 'mult_nivel1_correcto')
    op.drop_column('prueba_diagnostica', 'resta_tiempo_total')
    op.drop_column('prueba_diagnostica', 'resta_nivel2_correcto')
    op.drop_column('prueba_diagnostica', 'resta_nivel1_correcto')
    op.drop_column('prueba_diagnostica', 'suma_tiempo_total')
    op.drop_column('prueba_diagnostica', 'suma_nivel2_correcto')
    op.drop_column('prueba_diagnostica', 'suma_nivel1_correcto')
    op.add_column('perfil_estudiante', sa.Column('consecutivas_correctas', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('perfil_estudiante', sa.Column('total_correctas_nivel_actual', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('perfil_estudiante', sa.Column('fecha_ultima_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('perfil_estudiante', sa.Column('varianza_rendimiento', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.alter_column('perfil_estudiante', 'sesiones_en_nivel_actual',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('perfil_estudiante', 'velocidad_promedio',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('perfil_estudiante', 'precision_ultimos_15',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.drop_column('perfil_estudiante', 'fecha_actualizacion')
    op.drop_column('perfil_estudiante', 'fecha_creacion')
    op.drop_column('perfil_estudiante', 'dias_sin_practicar')
    op.drop_column('perfil_estudiante', 'ultima_actividad')
    op.drop_column('perfil_estudiante', 'alertas_activas')
    op.drop_column('perfil_estudiante', 'historial_promociones')
    op.drop_column('perfil_estudiante', 'practicas_perfectas_consecutivas')
    op.drop_column('perfil_estudiante', 'total_sesiones')
    op.drop_column('perfil_estudiante', 'umbral_promocion_personalizado')
    op.drop_column('perfil_estudiante', 'fecha_ultima_clasificacion')
    op.drop_column('perfil_estudiante', 'varianza_velocidad')
    op.drop_column('perfil_estudiante', 'consecutivas_correctas_div')
    op.drop_column('perfil_estudiante', 'consecutivas_correctas_mult')
    op.drop_column('perfil_estudiante', 'consecutivas_correctas_resta')
    op.drop_column('perfil_estudiante', 'consecutivas_correctas_suma')
    op.drop_index(op.f('ix_alerta_estudiante_id'), table_name='alerta_estudiante')
    op.drop_column('alerta_estudiante', 'fecha_resolucion')
    op.drop_column('alerta_estudiante', 'fecha_lectura')
    # ### end Alembic commands ###
