"""modificar sistema de autenticacion a codigos unicos

Revision ID: 62bd192fe6c2
Revises: 21889048861a
Create Date: 2026-01-06 21:19:49.244749+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bd192fe6c2'
down_revision: Union[str, None] = '21889048861a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
