"""add_puntos_totales_to_estudiante

Revision ID: 0092496bbdfc
Revises: 1e9b1f3ceef0
Create Date: 2026-02-24 13:30:30.129390+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0092496bbdfc'
down_revision: Union[str, None] = '1e9b1f3ceef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiante', sa.Column('puntos_totales', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudiante', 'puntos_totales')
    # ### end Alembic commands ###
