"""test

Revision ID: 21889048861a
Revises: 
Create Date: 2026-01-06 21:18:32.190297+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21889048861a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_desbloqueable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Enum('COLOR', 'FORMA', 'MUSICA', 'FONDO', 'FUENTE', name='tipocategoria'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categoria_desbloqueable_id'), 'categoria_desbloqueable', ['id'], unique=False)
    op.create_table('error_comun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('operacion_asociada', sa.String(length=50), nullable=True),
    sa.Column('patron_deteccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_comun_codigo'), 'error_comun', ['codigo'], unique=True)
    op.create_index(op.f('ix_error_comun_id'), 'error_comun', ['id'], unique=False)
    op.create_table('medalla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono_url', sa.String(length=500), nullable=True),
    sa.Column('condicion_obtencion', sa.JSON(), nullable=False),
    sa.Column('nivel_requerido', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medalla_codigo'), 'medalla', ['codigo'], unique=True)
    op.create_index(op.f('ix_medalla_id'), 'medalla', ['id'], unique=False)
    op.create_table('narrativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_narrativa_id'), 'narrativa', ['id'], unique=False)
    op.create_table('problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.Enum('SUMA', 'RESTA', 'MULTIPLICACION', 'DIVISION', name='operacion'), nullable=False),
    sa.Column('numero1', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('numero2', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('resultado', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('nivel_dificultad', sa.Integer(), nullable=False),
    sa.Column('cantidad_decimales', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problema_id'), 'problema', ['id'], unique=False)
    op.create_index(op.f('ix_problema_nivel_dificultad'), 'problema', ['nivel_dificultad'], unique=False)
    op.create_index(op.f('ix_problema_operacion'), 'problema', ['operacion'], unique=False)
    op.create_index(op.f('ix_problema_signature'), 'problema', ['signature'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('ESTUDIANTE', 'PROFESOR', name='tipousuario'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('desbloqueable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('asset_url', sa.String(length=500), nullable=True),
    sa.Column('requiere_problemas_correctos', sa.Integer(), nullable=False),
    sa.Column('es_premium', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_desbloqueable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desbloqueable_categoria_id'), 'desbloqueable', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_desbloqueable_codigo'), 'desbloqueable', ['codigo'], unique=True)
    op.create_index(op.f('ix_desbloqueable_id'), 'desbloqueable', ['id'], unique=False)
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_estudiante', sa.String(length=50), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('narrativa_seleccionada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['narrativa_seleccionada_id'], ['narrativa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiante_codigo_estudiante'), 'estudiante', ['codigo_estudiante'], unique=True)
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_profesor', sa.String(length=50), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('institucion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesor_codigo_profesor'), 'profesor', ['codigo_profesor'], unique=True)
    op.create_table('video_pista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problema_signature', sa.String(length=64), nullable=False),
    sa.Column('nivel_estudiante', sa.Integer(), nullable=False),
    sa.Column('narrativa_id', sa.Integer(), nullable=False),
    sa.Column('guion_texto', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('en_cache', sa.Boolean(), nullable=False),
    sa.Column('fecha_expiracion_cache', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['narrativa_id'], ['narrativa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_pista_id'), 'video_pista', ['id'], unique=False)
    op.create_index(op.f('ix_video_pista_narrativa_id'), 'video_pista', ['narrativa_id'], unique=False)
    op.create_index(op.f('ix_video_pista_problema_signature'), 'video_pista', ['problema_signature'], unique=False)
    op.create_table('desafio_grupal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('objetivo_cantidad', sa.Integer(), nullable=False),
    sa.Column('recompensa_texto', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desafio_grupal_id'), 'desafio_grupal', ['id'], unique=False)
    op.create_index(op.f('ix_desafio_grupal_profesor_id'), 'desafio_grupal', ['profesor_id'], unique=False)
    op.create_table('desafio_individual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problema_id'], ['problema.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desafio_individual_id'), 'desafio_individual', ['id'], unique=False)
    op.create_index(op.f('ix_desafio_individual_problema_id'), 'desafio_individual', ['problema_id'], unique=False)
    op.create_index(op.f('ix_desafio_individual_profesor_id'), 'desafio_individual', ['profesor_id'], unique=False)
    op.create_table('estadistica_estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('practicas_completadas', sa.Integer(), nullable=False),
    sa.Column('problemas_resueltos', sa.Integer(), nullable=False),
    sa.Column('problemas_correctos', sa.Integer(), nullable=False),
    sa.Column('tiempo_total_minutos', sa.Integer(), nullable=False),
    sa.Column('pistas_utilizadas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estadistica_estudiante_estudiante_id'), 'estadistica_estudiante', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_estadistica_estudiante_fecha'), 'estadistica_estudiante', ['fecha'], unique=False)
    op.create_index(op.f('ix_estadistica_estudiante_id'), 'estadistica_estudiante', ['id'], unique=False)
    op.create_table('estudiante_desbloqueable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('desbloqueable_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desbloqueo', sa.DateTime(), nullable=False),
    sa.Column('desbloqueado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['desbloqueable_id'], ['desbloqueable.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiante_desbloqueable_desbloqueable_id'), 'estudiante_desbloqueable', ['desbloqueable_id'], unique=False)
    op.create_index(op.f('ix_estudiante_desbloqueable_estudiante_id'), 'estudiante_desbloqueable', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_estudiante_desbloqueable_id'), 'estudiante_desbloqueable', ['id'], unique=False)
    op.create_table('estudiante_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=False),
    sa.Column('fecha_deteccion', sa.DateTime(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['error_comun.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['problema_id'], ['problema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiante_error_error_id'), 'estudiante_error', ['error_id'], unique=False)
    op.create_index(op.f('ix_estudiante_error_estudiante_id'), 'estudiante_error', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_estudiante_error_fecha_deteccion'), 'estudiante_error', ['fecha_deteccion'], unique=False)
    op.create_index(op.f('ix_estudiante_error_id'), 'estudiante_error', ['id'], unique=False)
    op.create_index(op.f('ix_estudiante_error_problema_id'), 'estudiante_error', ['problema_id'], unique=False)
    op.create_index(op.f('ix_estudiante_error_resuelto'), 'estudiante_error', ['resuelto'], unique=False)
    op.create_table('estudiante_medalla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('medalla_id', sa.Integer(), nullable=False),
    sa.Column('fecha_obtencion', sa.DateTime(), nullable=False),
    sa.Column('exhibida', sa.Boolean(), nullable=False),
    sa.Column('orden_exhibicion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['medalla_id'], ['medalla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiante_medalla_estudiante_id'), 'estudiante_medalla', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_estudiante_medalla_id'), 'estudiante_medalla', ['id'], unique=False)
    op.create_index(op.f('ix_estudiante_medalla_medalla_id'), 'estudiante_medalla', ['medalla_id'], unique=False)
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('codigo_grupo', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_codigo_grupo'), 'grupo', ['codigo_grupo'], unique=True)
    op.create_index(op.f('ix_grupo_id'), 'grupo', ['id'], unique=False)
    op.create_index(op.f('ix_grupo_profesor_id'), 'grupo', ['profesor_id'], unique=False)
    op.create_table('intento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_estudiante', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('es_correcto', sa.Boolean(), nullable=False),
    sa.Column('tiempo_resolucion', sa.Integer(), nullable=False),
    sa.Column('solicito_pista', sa.Boolean(), nullable=False),
    sa.Column('tipo_sesion', sa.Enum('PRACTICA', 'DESAFIO', 'REDENCION', name='tiposesion'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['problema_id'], ['problema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intento_es_correcto'), 'intento', ['es_correcto'], unique=False)
    op.create_index(op.f('ix_intento_estudiante_id'), 'intento', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_intento_id'), 'intento', ['id'], unique=False)
    op.create_index(op.f('ix_intento_problema_id'), 'intento', ['problema_id'], unique=False)
    op.create_index(op.f('ix_intento_timestamp'), 'intento', ['timestamp'], unique=False)
    op.create_index(op.f('ix_intento_tipo_sesion'), 'intento', ['tipo_sesion'], unique=False)
    op.create_table('perfil_estudiante',
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('nivel_actual', sa.Integer(), nullable=False),
    sa.Column('nivel_suma', sa.Integer(), nullable=False),
    sa.Column('nivel_resta', sa.Integer(), nullable=False),
    sa.Column('nivel_multiplicacion', sa.Integer(), nullable=False),
    sa.Column('nivel_division', sa.Integer(), nullable=False),
    sa.Column('consecutivas_correctas', sa.Integer(), nullable=False),
    sa.Column('total_correctas_nivel_actual', sa.Integer(), nullable=False),
    sa.Column('sesiones_en_nivel_actual', sa.Integer(), nullable=False),
    sa.Column('precision_ultimos_15', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('velocidad_promedio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('varianza_rendimiento', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fecha_ultima_promocion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('estudiante_id')
    )
    op.create_table('personalizacion_estudiante',
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('forma_boton_id', sa.Integer(), nullable=True),
    sa.Column('color_boton_id', sa.Integer(), nullable=True),
    sa.Column('musica_fondo_id', sa.Integer(), nullable=True),
    sa.Column('fondo_pantalla_id', sa.Integer(), nullable=True),
    sa.Column('fuente_texto_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['color_boton_id'], ['desbloqueable.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['fondo_pantalla_id'], ['desbloqueable.id'], ),
    sa.ForeignKeyConstraint(['forma_boton_id'], ['desbloqueable.id'], ),
    sa.ForeignKeyConstraint(['fuente_texto_id'], ['desbloqueable.id'], ),
    sa.ForeignKeyConstraint(['musica_fondo_id'], ['desbloqueable.id'], ),
    sa.PrimaryKeyConstraint('estudiante_id')
    )
    op.create_table('video_guardado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('fecha_guardado', sa.DateTime(), nullable=False),
    sa.Column('accesos', sa.Integer(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_pista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_guardado_estudiante_id'), 'video_guardado', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_video_guardado_id'), 'video_guardado', ['id'], unique=False)
    op.create_index(op.f('ix_video_guardado_video_id'), 'video_guardado', ['video_id'], unique=False)
    op.create_table('configuracion_practica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('nivel_dificultad', sa.Integer(), nullable=False),
    sa.Column('operaciones_permitidas', sa.JSON(), nullable=False),
    sa.Column('decimales_maximos', sa.Integer(), nullable=False),
    sa.Column('rango_min', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('rango_max', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('fecha_aplicacion', sa.DateTime(), nullable=False),
    sa.Column('aplicada_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aplicada_por'], ['profesor.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_practica_aplicada_por'), 'configuracion_practica', ['aplicada_por'], unique=False)
    op.create_index(op.f('ix_configuracion_practica_grupo_id'), 'configuracion_practica', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_configuracion_practica_id'), 'configuracion_practica', ['id'], unique=False)
    op.create_table('estudiante_desafio_individual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desafio_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['desafio_id'], ['desafio_individual.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiante_desafio_individual_desafio_id'), 'estudiante_desafio_individual', ['desafio_id'], unique=False)
    op.create_index(op.f('ix_estudiante_desafio_individual_estudiante_id'), 'estudiante_desafio_individual', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_estudiante_desafio_individual_id'), 'estudiante_desafio_individual', ['id'], unique=False)
    op.create_table('estudiante_grupo',
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('estudiante_id', 'grupo_id')
    )
    op.create_table('grupo_desafio',
    sa.Column('desafio_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('progreso_actual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['desafio_id'], ['desafio_grupal.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('desafio_id', 'grupo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo_desafio')
    op.drop_table('estudiante_grupo')
    op.drop_index(op.f('ix_estudiante_desafio_individual_id'), table_name='estudiante_desafio_individual')
    op.drop_index(op.f('ix_estudiante_desafio_individual_estudiante_id'), table_name='estudiante_desafio_individual')
    op.drop_index(op.f('ix_estudiante_desafio_individual_desafio_id'), table_name='estudiante_desafio_individual')
    op.drop_table('estudiante_desafio_individual')
    op.drop_index(op.f('ix_configuracion_practica_id'), table_name='configuracion_practica')
    op.drop_index(op.f('ix_configuracion_practica_grupo_id'), table_name='configuracion_practica')
    op.drop_index(op.f('ix_configuracion_practica_aplicada_por'), table_name='configuracion_practica')
    op.drop_table('configuracion_practica')
    op.drop_index(op.f('ix_video_guardado_video_id'), table_name='video_guardado')
    op.drop_index(op.f('ix_video_guardado_id'), table_name='video_guardado')
    op.drop_index(op.f('ix_video_guardado_estudiante_id'), table_name='video_guardado')
    op.drop_table('video_guardado')
    op.drop_table('personalizacion_estudiante')
    op.drop_table('perfil_estudiante')
    op.drop_index(op.f('ix_intento_tipo_sesion'), table_name='intento')
    op.drop_index(op.f('ix_intento_timestamp'), table_name='intento')
    op.drop_index(op.f('ix_intento_problema_id'), table_name='intento')
    op.drop_index(op.f('ix_intento_id'), table_name='intento')
    op.drop_index(op.f('ix_intento_estudiante_id'), table_name='intento')
    op.drop_index(op.f('ix_intento_es_correcto'), table_name='intento')
    op.drop_table('intento')
    op.drop_index(op.f('ix_grupo_profesor_id'), table_name='grupo')
    op.drop_index(op.f('ix_grupo_id'), table_name='grupo')
    op.drop_index(op.f('ix_grupo_codigo_grupo'), table_name='grupo')
    op.drop_table('grupo')
    op.drop_index(op.f('ix_estudiante_medalla_medalla_id'), table_name='estudiante_medalla')
    op.drop_index(op.f('ix_estudiante_medalla_id'), table_name='estudiante_medalla')
    op.drop_index(op.f('ix_estudiante_medalla_estudiante_id'), table_name='estudiante_medalla')
    op.drop_table('estudiante_medalla')
    op.drop_index(op.f('ix_estudiante_error_resuelto'), table_name='estudiante_error')
    op.drop_index(op.f('ix_estudiante_error_problema_id'), table_name='estudiante_error')
    op.drop_index(op.f('ix_estudiante_error_id'), table_name='estudiante_error')
    op.drop_index(op.f('ix_estudiante_error_fecha_deteccion'), table_name='estudiante_error')
    op.drop_index(op.f('ix_estudiante_error_estudiante_id'), table_name='estudiante_error')
    op.drop_index(op.f('ix_estudiante_error_error_id'), table_name='estudiante_error')
    op.drop_table('estudiante_error')
    op.drop_index(op.f('ix_estudiante_desbloqueable_id'), table_name='estudiante_desbloqueable')
    op.drop_index(op.f('ix_estudiante_desbloqueable_estudiante_id'), table_name='estudiante_desbloqueable')
    op.drop_index(op.f('ix_estudiante_desbloqueable_desbloqueable_id'), table_name='estudiante_desbloqueable')
    op.drop_table('estudiante_desbloqueable')
    op.drop_index(op.f('ix_estadistica_estudiante_id'), table_name='estadistica_estudiante')
    op.drop_index(op.f('ix_estadistica_estudiante_fecha'), table_name='estadistica_estudiante')
    op.drop_index(op.f('ix_estadistica_estudiante_estudiante_id'), table_name='estadistica_estudiante')
    op.drop_table('estadistica_estudiante')
    op.drop_index(op.f('ix_desafio_individual_profesor_id'), table_name='desafio_individual')
    op.drop_index(op.f('ix_desafio_individual_problema_id'), table_name='desafio_individual')
    op.drop_index(op.f('ix_desafio_individual_id'), table_name='desafio_individual')
    op.drop_table('desafio_individual')
    op.drop_index(op.f('ix_desafio_grupal_profesor_id'), table_name='desafio_grupal')
    op.drop_index(op.f('ix_desafio_grupal_id'), table_name='desafio_grupal')
    op.drop_table('desafio_grupal')
    op.drop_index(op.f('ix_video_pista_problema_signature'), table_name='video_pista')
    op.drop_index(op.f('ix_video_pista_narrativa_id'), table_name='video_pista')
    op.drop_index(op.f('ix_video_pista_id'), table_name='video_pista')
    op.drop_table('video_pista')
    op.drop_index(op.f('ix_profesor_codigo_profesor'), table_name='profesor')
    op.drop_table('profesor')
    op.drop_index(op.f('ix_estudiante_codigo_estudiante'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_desbloqueable_id'), table_name='desbloqueable')
    op.drop_index(op.f('ix_desbloqueable_codigo'), table_name='desbloqueable')
    op.drop_index(op.f('ix_desbloqueable_categoria_id'), table_name='desbloqueable')
    op.drop_table('desbloqueable')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_problema_signature'), table_name='problema')
    op.drop_index(op.f('ix_problema_operacion'), table_name='problema')
    op.drop_index(op.f('ix_problema_nivel_dificultad'), table_name='problema')
    op.drop_index(op.f('ix_problema_id'), table_name='problema')
    op.drop_table('problema')
    op.drop_index(op.f('ix_narrativa_id'), table_name='narrativa')
    op.drop_table('narrativa')
    op.drop_index(op.f('ix_medalla_id'), table_name='medalla')
    op.drop_index(op.f('ix_medalla_codigo'), table_name='medalla')
    op.drop_table('medalla')
    op.drop_index(op.f('ix_error_comun_id'), table_name='error_comun')
    op.drop_index(op.f('ix_error_comun_codigo'), table_name='error_comun')
    op.drop_table('error_comun')
    op.drop_index(op.f('ix_categoria_desbloqueable_id'), table_name='categoria_desbloqueable')
    op.drop_table('categoria_desbloqueable')
    # ### end Alembic commands ###
