"""add_configuracion_practica

Revision ID: f632343d3b38
Revises: add_organizacion_v1
Create Date: 2026-02-23 20:48:06.561089+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'f632343d3b38'
down_revision: Union[str, None] = 'add_organizacion_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _col(table: str, column: str) -> bool:
    return column in [c['name'] for c in inspect(op.get_bind()).get_columns(table)]


def upgrade() -> None:
    # Crear enum si no existe (puede ya existir de migraciones anteriores)
    op.execute("DO $$ BEGIN CREATE TYPE nivelpista AS ENUM ('NIVEL_1', 'NIVEL_2', 'NIVEL_3'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generacion_llm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=True),
    sa.Column('tema', sa.String(length=50), nullable=True),
    sa.Column('prompt_usado', sa.Text(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('respuesta_llm', sa.Text(), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('tiempo_generacion_ms', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problema_id'], ['problema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generacion_llm_fecha'), 'generacion_llm', ['fecha'], unique=False)
    op.create_index(op.f('ix_generacion_llm_id'), 'generacion_llm', ['id'], unique=False)
    op.create_table('video_temporal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_educativo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_temporal_id'), 'video_temporal', ['id'], unique=False)
    # La migración 'test' (21889048861a) creó configuracion_practica con esquema viejo.
    # La eliminamos para recrearla con el esquema correcto (aplicada_por_profesor_id, etc.).
    op.execute("DROP TABLE IF EXISTS configuracion_practica CASCADE")
    op.create_table('configuracion_practica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('aplicada_por_profesor_id', sa.Integer(), nullable=False),
    sa.Column('operaciones_permitidas', sa.JSON(), nullable=False),
    sa.Column('niveles_permitidos', sa.JSON(), nullable=False),
    sa.Column('rango_min', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('rango_max', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('decimales_maximos', sa.Integer(), nullable=False),
    sa.Column('pistas_habilitadas', sa.JSON(), nullable=False),
    sa.Column('fecha_aplicacion', sa.DateTime(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aplicada_por_profesor_id'], ['profesor.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_practica_grupo_id'), 'configuracion_practica', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_configuracion_practica_id'), 'configuracion_practica', ['id'], unique=False)
    op.create_table('uso_pista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=False),
    sa.Column('nivel_pista', postgresql.ENUM('NIVEL_1', 'NIVEL_2', 'NIVEL_3', name='nivelpista', create_type=False), nullable=False),
    sa.Column('puntos_gastados', sa.Integer(), nullable=True),
    sa.Column('generada_llm', sa.Boolean(), nullable=True),
    sa.Column('contenido_pista', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['problema_id'], ['problema.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesion_practica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uso_pista_estudiante_id'), 'uso_pista', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_uso_pista_fecha'), 'uso_pista', ['fecha'], unique=False)
    op.create_index(op.f('ix_uso_pista_id'), 'uso_pista', ['id'], unique=False)
    op.alter_column('desbloqueable', 'nivel_minimo_requerido',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('desbloqueable', 'orden',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('desbloqueable', 'es_tema_inicial',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('desbloqueable', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('desbloqueable', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('fk_estudiante_organizacion_id'), 'estudiante', type_='foreignkey')
    op.create_foreign_key(None, 'estudiante', 'organizacion', ['organizacion_id'], ['id'])
    op.drop_column('estudiante', 'puntos_totales')
    op.alter_column('estudiante_desbloqueable', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('estudiante_medalla', 'fecha_obtencion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('estudiante_medalla', 'notificada',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('medalla', 'orden',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('medalla', 'es_secreta',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('medalla', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('medalla', 'activa',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('organizacion', 'pais',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('organizacion', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizacion', 'activa',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('organizacion_codigo_key'), 'organizacion', type_='unique')
    op.drop_index(op.f('ix_organizacion_codigo'), table_name='organizacion')
    op.create_index(op.f('ix_organizacion_codigo'), 'organizacion', ['codigo'], unique=True)
    # personalizacion_estudiante: migración 5 ya crea la tabla con esquema nuevo.
    # Solo agregamos columnas si no existen, y eliminamos las viejas si existen.
    if not _col('personalizacion_estudiante', 'tema_activo_id'):
        op.add_column('personalizacion_estudiante', sa.Column('tema_activo_id', sa.Integer(), nullable=True))
    if not _col('personalizacion_estudiante', 'fondo_activo_id'):
        op.add_column('personalizacion_estudiante', sa.Column('fondo_activo_id', sa.Integer(), nullable=True))
    if not _col('personalizacion_estudiante', 'musica_activa_id'):
        op.add_column('personalizacion_estudiante', sa.Column('musica_activa_id', sa.Integer(), nullable=True))
    if not _col('personalizacion_estudiante', 'color_fondo'):
        op.add_column('personalizacion_estudiante', sa.Column('color_fondo', sa.String(length=7), nullable=True))
    if not _col('personalizacion_estudiante', 'color_texto'):
        op.add_column('personalizacion_estudiante', sa.Column('color_texto', sa.String(length=7), nullable=True))
    if not _col('personalizacion_estudiante', 'color_botones'):
        op.add_column('personalizacion_estudiante', sa.Column('color_botones', sa.String(length=7), nullable=True))
    if not _col('personalizacion_estudiante', 'efectos_activos'):
        op.add_column('personalizacion_estudiante', sa.Column('efectos_activos', sa.JSON(), nullable=True))
    if not _col('personalizacion_estudiante', 'fecha_actualizacion'):
        op.add_column('personalizacion_estudiante', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
    # FKs para columnas nuevas: solo si la columna existe pero el FK no (migración 5 ya los crea)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_name = 'personalizacion_estudiante'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND kcu.column_name = 'fondo_activo_id'
            ) THEN
                ALTER TABLE personalizacion_estudiante
                    ADD CONSTRAINT pe_fondo_fk FOREIGN KEY (fondo_activo_id) REFERENCES desbloqueable(id);
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_name = 'personalizacion_estudiante'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND kcu.column_name = 'musica_activa_id'
            ) THEN
                ALTER TABLE personalizacion_estudiante
                    ADD CONSTRAINT pe_musica_fk FOREIGN KEY (musica_activa_id) REFERENCES desbloqueable(id);
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_name = 'personalizacion_estudiante'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND kcu.column_name = 'tema_activo_id'
            ) THEN
                ALTER TABLE personalizacion_estudiante
                    ADD CONSTRAINT pe_tema_fk FOREIGN KEY (tema_activo_id) REFERENCES desbloqueable(id);
            END IF;
        END $$;
    """)
    # Eliminar columnas viejas (del esquema original de la migración test) si todavía existen
    if _col('personalizacion_estudiante', 'fondo_pantalla_id'):
        op.drop_column('personalizacion_estudiante', 'fondo_pantalla_id')
    if _col('personalizacion_estudiante', 'color_boton_id'):
        op.drop_column('personalizacion_estudiante', 'color_boton_id')
    if _col('personalizacion_estudiante', 'fecha_ultima_modificacion'):
        op.drop_column('personalizacion_estudiante', 'fecha_ultima_modificacion')
    if _col('personalizacion_estudiante', 'forma_boton_id'):
        op.drop_column('personalizacion_estudiante', 'forma_boton_id')
    if _col('personalizacion_estudiante', 'fuente_texto_id'):
        op.drop_column('personalizacion_estudiante', 'fuente_texto_id')
    if _col('personalizacion_estudiante', 'musica_fondo_id'):
        op.drop_column('personalizacion_estudiante', 'musica_fondo_id')
    # enunciado_tematico y tema en problema: migración 5 los agrega, esta migración los elimina
    # (migración 20260303 los vuelve a agregar después)
    if _col('problema', 'enunciado_tematico'):
        op.drop_column('problema', 'enunciado_tematico')
    if _col('problema', 'tema'):
        op.drop_column('problema', 'tema')
    op.drop_constraint(op.f('fk_profesor_organizacion_id'), 'profesor', type_='foreignkey')
    op.create_foreign_key(None, 'profesor', 'organizacion', ['organizacion_id'], ['id'])
    op.alter_column('sesion_practica', 'puntos_ganados',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transaccion_puntos', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.add_column('video_guardado', sa.Column('visto', sa.Boolean(), nullable=True))
    op.add_column('video_guardado', sa.Column('progreso_segundos', sa.Integer(), nullable=True))
    op.alter_column('video_guardado', 'fecha_guardado',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_video_guardado_video_id'), table_name='video_guardado')
    op.create_index(op.f('ix_video_guardado_fecha_guardado'), 'video_guardado', ['fecha_guardado'], unique=False)
    op.drop_constraint(op.f('video_guardado_video_id_fkey'), 'video_guardado', type_='foreignkey')
    op.create_foreign_key(None, 'video_guardado', 'video_educativo', ['video_id'], ['id'])
    op.drop_column('video_guardado', 'accesos')
    op.drop_column('video_guardado', 'ultimo_acceso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_guardado', sa.Column('ultimo_acceso', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('video_guardado', sa.Column('accesos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_guardado', type_='foreignkey')
    op.create_foreign_key(op.f('video_guardado_video_id_fkey'), 'video_guardado', 'video_pista', ['video_id'], ['id'])
    op.drop_index(op.f('ix_video_guardado_fecha_guardado'), table_name='video_guardado')
    op.create_index(op.f('ix_video_guardado_video_id'), 'video_guardado', ['video_id'], unique=False)
    op.alter_column('video_guardado', 'fecha_guardado',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('video_guardado', 'progreso_segundos')
    op.drop_column('video_guardado', 'visto')
    op.alter_column('transaccion_puntos', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('sesion_practica', 'puntos_ganados',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_constraint(None, 'profesor', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profesor_organizacion_id'), 'profesor', 'organizacion', ['organizacion_id'], ['id'], ondelete='SET NULL')
    op.add_column('problema', sa.Column('tema', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('problema', sa.Column('enunciado_tematico', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personalizacion_estudiante', sa.Column('musica_fondo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('personalizacion_estudiante', sa.Column('fuente_texto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('personalizacion_estudiante', sa.Column('forma_boton_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('personalizacion_estudiante', sa.Column('fecha_ultima_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('personalizacion_estudiante', sa.Column('color_boton_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('personalizacion_estudiante', sa.Column('fondo_pantalla_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'personalizacion_estudiante', type_='foreignkey')
    op.drop_constraint(None, 'personalizacion_estudiante', type_='foreignkey')
    op.drop_constraint(None, 'personalizacion_estudiante', type_='foreignkey')
    op.drop_column('personalizacion_estudiante', 'fecha_actualizacion')
    op.drop_column('personalizacion_estudiante', 'efectos_activos')
    op.drop_column('personalizacion_estudiante', 'color_botones')
    op.drop_column('personalizacion_estudiante', 'color_texto')
    op.drop_column('personalizacion_estudiante', 'color_fondo')
    op.drop_column('personalizacion_estudiante', 'musica_activa_id')
    op.drop_column('personalizacion_estudiante', 'fondo_activo_id')
    op.drop_column('personalizacion_estudiante', 'tema_activo_id')
    op.drop_index(op.f('ix_organizacion_codigo'), table_name='organizacion')
    op.create_index(op.f('ix_organizacion_codigo'), 'organizacion', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('organizacion_codigo_key'), 'organizacion', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('organizacion', 'activa',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('organizacion', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('organizacion', 'pais',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Colombia'::character varying"),
               existing_nullable=True)
    op.alter_column('medalla', 'activa',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('medalla', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('medalla', 'es_secreta',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('medalla', 'orden',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('estudiante_medalla', 'notificada',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('estudiante_medalla', 'fecha_obtencion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('estudiante_desbloqueable', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('estudiante', sa.Column('puntos_totales', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'estudiante', type_='foreignkey')
    op.create_foreign_key(op.f('fk_estudiante_organizacion_id'), 'estudiante', 'organizacion', ['organizacion_id'], ['id'], ondelete='SET NULL')
    op.alter_column('desbloqueable', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('desbloqueable', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('desbloqueable', 'es_tema_inicial',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('desbloqueable', 'orden',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('desbloqueable', 'nivel_minimo_requerido',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=False)
    op.drop_index(op.f('ix_uso_pista_id'), table_name='uso_pista')
    op.drop_index(op.f('ix_uso_pista_fecha'), table_name='uso_pista')
    op.drop_index(op.f('ix_uso_pista_estudiante_id'), table_name='uso_pista')
    op.drop_table('uso_pista')
    op.drop_index(op.f('ix_configuracion_practica_id'), table_name='configuracion_practica')
    op.drop_index(op.f('ix_configuracion_practica_grupo_id'), table_name='configuracion_practica')
    op.drop_table('configuracion_practica')
    op.drop_index(op.f('ix_video_temporal_id'), table_name='video_temporal')
    op.drop_table('video_temporal')
    op.drop_index(op.f('ix_generacion_llm_id'), table_name='generacion_llm')
    op.drop_index(op.f('ix_generacion_llm_fecha'), table_name='generacion_llm')
    op.drop_table('generacion_llm')
    # ### end Alembic commands ###
